# permissions for end users to view deployassists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployassist-viewer-role
rules:
- apiGroups:
  - deployassist.apiextensions.k8s.io
  resources:
  - deployassists
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deployassist.apiextensions.k8s.io
  resources:
  - deployassists/status
  verbs:
  - get
