# permissions for end users to edit deployassists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployassist-editor-role
rules:
- apiGroups:
  - deployassist.apiextensions.k8s.io
  resources:
  - deployassists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployassist.apiextensions.k8s.io
  resources:
  - deployassists/status
  verbs:
  - get
